runtime: nodejs20
service: backend

env_variables:
  NODE_ENV: "production"

handlers:
  - url: /.*
    secure: always
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50