runtime: nodejs20
service: default

handlers:
  # Serve built static assets (JS, CSS, images)
  - url: /(assets/.*)
    static_dir: dist/assets
    secure: always

  # SPA fallback: all other routes -> index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 5