runtime: nodejs20

service: backend

env_variables:
  NODE_ENV: "production"
  SUPABASE_URL: {{ $secrets.SUPABASE_URL }}
  SUPABASE_SERVICE_ROLE_KEY: {{ $secrets.SUPABASE_SERVICE_ROLE_KEY }}

handlers:
  - url: /.*
    secure: always
    script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 5