runtime: nodejs20

service: backend

env_variables:
  NODE_ENV: "production"
  GCP_PROJECT: "decal-478508"

handlers:
  - url: /.*
    secure: always
    script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 5